@startuml
== Time graph view is open ==
actor User
activate "Theia Trace"
activate "Trace Server"
User -> "Theia Trace": Enter filter string
note left: cpu==1 && tid==1234
"Theia Trace" -> "Trace Server": fetch tree model
"Trace Server" -> "Theia Trace": success (200)
loop nbVisibleRows
"Theia Trace" -> "Trace Server": fetch row model(time range, filter)
"Trace Server" -> "Theia Trace": success (200)
end
note right: Repeat for all \nvisible rows or \n row cache size
"Theia Trace" -> "Theia Trace": Visualize tree model
"Theia Trace" -> "Theia Trace": Visualize row models
note left: Highlight states if filter matches\n or dim non-matched states.
@enduml